---
title: "Interview Prep"
format: 
  html: 
    embed-resources: true
editor: source
---
  
\#pipelinematters  
\#viewsmyown

Another career analyst framework, hopefully general enough to be broadly useful.
Sharing if also helpful to you. Aimed at early career and new grads without
extensive prior experience.
  
---

### First, congrats on the interview! 

Landing an interview is a big step. If we assume most entry-level positions receive
200+ applications, you've already achieved a noteworthy milestone. The organization is 
seriously considering you as a candidate and wants to learn more about you and your experience. 

Now:

---

### Do your research.

Try to find out the org's interview structure, questions, technical elements. This is the
time to let your ~~internet sleuthing~~ research chops shine. Find out:  

- How many rounds are there in the process?
- Are interviews structured as group or individual interviews?
- Are there any technical exams? Exams are sometimes used as an initial screen.
- Are there any assignments, case interviews, technical interviews? These may require
significant preparation and familiarity to pass. Potential formats:
  1. Take-home: The recruiter asks you to pick a date. Once set, they send you an assignment
  similar to their work, and you have [X] hours to complete and return it.
  2. Technical interviews: As part of an interview process, the hiring 
  manager either requests you walk through a technical problem live or gives you [X]
  hours to walk through it on your own, then send or present your analysis to the team.
  3. Case interviews: Typically used in management consulting, these interviews walk 
  through a prospective client interaction designed to test your demeanor and
  problem-solving/quantitative abilities. If you're applying for an entry-level role,
  you may need a couple months to prepare. 

Sources of information:

- Ask/email recruiters about the recruitment process and interview structure.
- Talk to current and former employees to understand their experience.
- Look on the company's [LinkedIn](https://www.linkedin.com/) page.
- Look on [Glassdoor](https://www.glassdoor.com/index.htm), likely the most useful
online resource for interview questions. Other Q&A boards like 
[Reddit](https://www.reddit.com/) or [Quora](https://www.quora.com/) could also be helpful.*

\* As with all information online, take what you find with a grain of salt. Try to confirm
through an org contact.

---

### Practice.

> In interviewing, (nearly) all practice is good practice.  

Interviewing is like any other skill: you get better with practice. You'll interview
over the course of your professional life. Any time you invest in improving
will come in handy down the line.  

Once you have a list of practice interview questions (see below), practice, practice, practice.  
Write and speak your responses out loud. Ask your friends, classmates, or family if they'd be 
willing to conduct a mock interview. 

Your responses should:  
- be **focused, two minutes tops.** Don't ramble.   
- be **tailored to the org,** which shows your prep.  
- **address their needs** for the role. Does the job description say detail-oriented?
Give examples showing you're detail-oriented.  
- **help you put your best foot forward:** demonstrated knowledge and experience, 
critical thinking, times when you've shown good judgment or leadership ability. 

---

### Briefcase test.

As much as possible, show off **actual** work product: papers, projects, or code repos. 

- If you're a student or recent grad, come prepared with hard copies of one or two
papers, printed in color, ideally with calculations or code. The more relevant, the better.  
- In particular:
  - Work vetted through a formal publication process.
  - Work published online by an org you can link to.
  - Papers you've received positive feedback on.
  - Online portfolios they can review.
  - Code you've posted online, even for a personal or volunteer project.*
  
\* *Before posting code online:* If you wrote the code for a specific org, find out
their policies on making it publicly available. Some places are happy to have you
post; others consider it a legal matter, a security risk, or the org's proprietary IP.

---

### Questions they might ask you:

>"Tell me about yourself and why you applied for this position."  

- Nearly *100%* chance you'll be asked this question, so practice answering it.
- *Time your answer* to this question. It shouldn't exceed 2 minutes,
which shows your focus and preparation.  

>"Tell me a time when... "  

- These are great questions. They're designed to understand how you approach your work,
what role you play on a team, how you collaborate with others, how you resolve 
disagreements, how you demonstrate leadership, how you deal with challenges,
whether you can teach yourself new skills, whether you're "teachable" and can
take needed guidance/course-correction.  
- Think of a few lessons from each of your prior experiences. You can pull from
part-time jobs, internships, or group projects if you haven't had a full-time job yet.
Write out what you learned from each. How have you put your learning into practice? 
How did you grow from those experiences?  
- *Don't* speak in hypotheticals. Give concrete examples.  
- Pay attention to what's asked: their questions often describe the dynamics and 
challenges of the current team.  

>"Explain [a technical process you'll use] in plain English."

- A lot of technical or specialized work interfaces with nontechnical roles or roles
that don't share the same expertise, whether across a team, an org, or between
an org and its clients. **Communication is key to that work.**
- If you have a technical skillset, interviewers will frequently ask you to explain
some part of this work "in plain English," to a curious but nontechnical audience.

---

### Questions you might ask them:

Interviewing is a two-way street. Any good org should save at least five minutes
for you to ask questions. They're judging you by your questions; try not to ask anything
obvious you can easily Google or find out other ways. 

Be cautious if asking questions they have hard constraints or sensitivities around answering. 
You're unlikely to get good information from their responses, so why ask?
Find another way to get that information.

**Information you need from an interview:**

You owe it to yourself to do your own desk research on these questions as well, 
but it's important to get the org's take on:

- What are their expectations for the role? What are your expectations, and do 
they align? Are their expectations clear and realistic? How will they evaluate you?
- What's this role like day-to-day? Will you be using skills that actively promote your
development?
- What's the team like? Can you get a sense of their dynamic? How is responsibility
shared? Is the work collaborative or individual? Does the team share information 
and resources, or do analysts knowledge-hoard and/or compete?
- Where does the team sit within the org? How is the team viewed by the org? How
is the team's work utilized by other teams?
- What's the org like? How does it position itself in its industry? What's its
business model? Can you draw up a rough SWOT analysis to understand how they see themselves
and their environment?
- How is analyst performance incentivized? What skills/traits are valued? What achievements
or types of work are rewarded? Incentives can tell you a lot about org culture through 
"revealed preferences": what activity the org tangibly rewards.
- Which positions, types of work, contracts, etc are seen as "core" or "central" to the
business mission, and which are "auxiliary" nice-to-haves but not essential? 
Orgs frequently value "auxiliary" roles differently: you may have more "sticks" than
"carrots"; your effort may be taken for granted and your achievements may be invisible; 
your position may also be at-risk when the org cuts staff.

Standard questions to ask them:  

**The role:**

Day-to-day:

- What's the typical "day" in this job? What does the day-to-day look like? What skills
does it use and develop over time?  
- What does "success" look like in this role? What would you be expected to achieve at
one month, six months, one year? What metrics are used?
- What does the mix of collaborative vs. individual work look like?
- How is work shared? Do analysts on the team cover different portfolios, or are 
they generalists? If they have different portfolios, how did they come by their 
portfolio topics? Do people rotate through topics, or do people always cover the same topics?

Development over time:

- What does growth in this role look like? Is there a typical trajectory for this position?
What have previous analysts gone on to do?
- What training or resources are available for analyst development? How do analysts
try out or learn new skills? If after a couple of years in your role, you're interested
in a stretch assignment, detail, or other type of work, is there room for that?

**The org:** 

- Where does the org's "business" come from? How is it funded? Who are its clients and
how do they use the org's work? What's the "mix" of business in each client type?  
- Is there cyclicality or "busy periods"/"slow periods" in the org's work?  


Keep an eye out for red flags. Jacqueline Nolis and Emily Robinson created
a [great list](https://jnolis.com/blog/red_flags/) of a few to watch out for when
interviewing for data science roles. To this, I'd add:  

- 


---

### Interview prep matrix

Draw four quandrants on a piece of paper. In each corner, organize your thinking on:

1. Their 





---

### Best of luck!
  
  