---
title: "General Search Tips"
format: html
editor: source
---

\#pipelinematters  
\#viewsmyown

---

### Other Search Resources

Over the years, I've stumbled on a few great resources and personally found the list below helpful (your mileage may vary):  

- The podcast [Build a Career in Data Science, by Jacqueline Nolis and Emily Robinson](https://podcast.bestbook.cool/).
  The world of data science is changing with the advent of Claude Code, but I'd still highly recommend reviewing these
  podcast episodes for insightful, frank discussions about analyst careers. The podcast is a companion to their excellent book, [Build A Career in Data Science](https://www.manning.com/books/build-a-career-in-data-science?utm_source=buildcareer&utm_medium=affiliate&utm_campaign=book_robinson4_build_3_10_20&utm_content=number2&a_aid=buildcareer&a_bid=e9fbded0). I've heard Dr. Nolis speak and find both authors enormously inspiring. 

- [The 2-Hour Job Search, by Steve Dalton](https://2hourjobsearch.com/), possibly available through your local library. The book's written as an approachable instruction manual that takes "build a network" as the start of a conversation, not the end of a conversation. For a bit about the book, listen to [his radio interview](https://2hourjobsearch.com/articles). (I don't receive compensation for this rec or anything else on this blog; just like his approach.)  


### General Search Tips

> Develop a way to organize and track your job search.

Be organized in your job search. It doesn't matter what your tracking system looks like, but find or make one that works for you. This could be as simple as a spreadsheet listing the positions and places you've applied to: 

| Org of Interest | Position | Date Applied | Research Notes | Date Followed Up | 
| --------------- | -------- | ------------ | -------------- | ---------------- |
| Cool Place |  Cool Job | 1/1/2030 | A few notes from an informational interview | 1/14/2030 (two weeks later) |
| Another Cool Place | Another Cool Job | 1/2/2030 | A few notes from searching online | 1/15/2030 (two weeks later) |

Tracking helps you stay focused. Equally importantly, it serves as a visible record of your effort and the work you've put in. Some parts of a job search are beyond your ability to control, but you can manage organization.  

> Referrals.

Look carefully at places where you may have classmates, friends, or former colleagues. Internal referrals never guarantee a job, but they may increase your chances of being interviewed. Having someone who can speak credibly about your work helps reassure potential employers about your abilities. It makes you more of a known entity.  

> "Don't start complaining about your job search until you've sent >100 applications."

Best job search advice I received as an early career analyst. Job searches can be marathons. It's crucial to pace yourself by moderating your expectations around length and outcomes so you're not easily discouraged. BLS labor statistics for 2025 show it took unemployed folks an [average of 5-6 months](https://www.bls.gov/news.release/empsit.t12.htm) to find a new job. 

> Don't neglect your family, friends, health, and sense of curiosity.

All job hunts are stressful, even under the best of circumstances. Where possible, take time with your family and friends. Get outside and exercise a bit. Look after your sleep and diet. If you have a professional community, stay active in that community and use it to network and explore new things. Budget some time to pick up a tool or technique you've been meaning to learn. 

> Job hunting is easier as a team sport.

If you're in school or your work cohort is searching simultaneously, consider forming a job search study group. Get tips on your process, keep each other motivated, proofread others' application materials, and run practice interviews. 

