---
title: "Work as Training"
format: html
---

\#pipelinematters  
\#viewsmyown

---

> In an ideal world, your work *is* your training.  


It's hard to overstate this.  

-  You don't *need* additional training if your work pushes you to improve in the direction you're seeking. 
-  If your work contributes to your development, you have a better sense of what any additional training should target.  

This is much easier said than done. It’s honestly tough to find work utilizing the exact skills you hope to build. If you’re in such a role, congratulations! You’ve won the growth lottery.  

### Time use at work 

When thinking about your development, understand how you're using time at work and how it contributes to your growth.  

Everyone has three classes of work:  

-  <font color="#82C3D9">**Class A**:</font> CV-worthy accomplishments. Highlights you’re legitimately proud of, that you brag to your friends about, that you’d describe in a job interview.  

-  <font color="#82C3D9">**Class B**:</font> What’s on the tin. The main focus of your daily work. Ideally this still helps you grow, but it’s more routine.  

-  <font color="#82C3D9">**Class C**:</font> Other tasks, potentially extraneous, that you don’t prioritize but become part of your responsibilities.  

You can roughly track how you spend your time. How is your time divided among these three classes of work?  

Where possible, try to focus your time on Class A and B work.  

-  If that’s happening, tell your manager how happy you are with this scope of work! Your manager needs to hear this; it shows your appreciation.      
-  If that’s not happening, can you discuss the work you'd prefer with your manager? If you've gently raised this question a few times and the response left you discouraged, it's a sign you may need to consider alternatives.  

It’s okay—even good—if the skills you want to develop change over time. You can adjust Class A/B/C work classes to reflect your new priorities.  

### How to train when your work is not your training

Commiserations! Most folks you know have been here at some point in their careers. It's demoralizing, so hang in there.  

<font color="#82C3D9">**At work**:</font> 

-  Solicit other work from those around you.  
-  Ask for side projects or short-term stretch projects—if possible, even if they take time outside work.  

<font color="#82C3D9">**Outside work**:</font> 

-  Join a professional association, meet-up group, or other forum. Be active in this group. Use it to cross-train, network, and seek advice.  
-  If possible, do external work, either paid or unpaid. Anything that gets you credible, demonstrable experience using skills you want to develop.  

### Ask for and actively incorporate feedback

Getting quick, practicable, constructive feedback on short-term assignments is essential to growth. It can come from anywhere. 

-  Constantly solicit feedback and thank the people who give you feedback.  
-  Be teachable. If you trust and respect the feedback-giver, remember what they’ve told you to change and adjust as necessary. Actively demonstrate your capacity to learn.  
-  Reverse feedback: If you see someone around you who excels in an area you hope to improve, tell them so! Ask if you can interview them about it. Can you learn from what they do well?

### Benchmarking exercises

Every 2-4 years (or some other suitable interval), plan to:  

-  Apply for positions that represent next steps you’d be interested in.   
-  Collect these positions’ required skills and accomplishments and assess where you have gaps. These gaps can be used for training.  
-  Interview for them! Where possible, interview to assess your own ability as well as for practice. You’ll interview over the course of your career, so practice matters.  

Benchmarking is highly credible feedback on our growth and abilities. It also reminds us that what we do is a choice. Choice in what we do is one of the most valuable gifts we can give ourselves. It gives us agency.  

Best of luck!

